# github: [ZacKienzle2]
# patreon: ZacKienzle2
# open_collective: ZacKienzle2
# ko_fi: ZacKienzle2
# tidelift: pkg-platform/ZacKienzle2
# liberapay: ZacKienzle2
# polar: ZacKienzle2
# buy_me_a_coffee: ZacKienzle2
# custom: ["https://example.com/donate"]
