rules:
  template-injection:
    ignore:
      - release.yml:50:11
  excessive-permissions:
    ignore: []
  unpinned-uses:
    ignore: []
    config:
      policies:
        "actions/*": ref-pin
        "github/codeql-action/*": ref-pin
        "*": any
